name: my_tractor
description: Tractor Ordering application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  json_annotation: ^4.8.1
  get: ^4.6.6
  get_it: ^7.6.4
  # Hive Dependency
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  freezed_annotation: ^2.4.1
  flutter_polyline_points: ^2.0.0
  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  flutter_svg: ^2.0.7
  rename: ^3.0.0
  firebase_core: ^2.17.0
  cloud_firestore: ^4.9.3
  firebase_auth: ^4.10.1
  geolocator: ^10.1.0
  custom_info_window: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/tractor.png

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Black.ttf
        - asset: assets/fonts/DMSans-Bold.ttf
        - asset: assets/fonts/DMSans-ExtraBold.ttf
        - asset: assets/fonts/DMSans-ExtraLight.ttf
        - asset: assets/fonts/DMSans-Light.ttf
        - asset: assets/fonts/DMSans-Medium.ttf
        - asset: assets/fonts/DMSans-Regular.ttf
        - asset: assets/fonts/DMSans-SemiBold.ttf
        - asset: assets/fonts/DMSans-Thin.ttf
